### ISSUE TITLE
[Migration] Update cases for set migration bandwidth 

### ISSUE THREAD

**Issue by dzhengfy** [autotest/tp-libvirt#1676]
There are already some existing cases for migration speed, like virsh.migrate_set_get_speed.
Here we have some more requirements, like 
- set/get migration speed for shutoff/running guest 
- set/get migration speed before or during migration
- get default migration speed for shutoff/running guest + migration

**Comment by balamuruhans** [comment]
@dzhengfy can you share me the thought process behind these scenarios, like is there a customer scenarios around it or any new code changes went in recently etc.,

**Comment by dzhengfy** [comment]
@balamuruhans , these scenarios are only from our feature owner's requirements. No new code changes recently. Thanks.

**Comment by dzhengfy** [comment]
Add cases for during migration in https://github.com/autotest/tp-libvirt/pull/2019
