### ISSUE TITLE
[Migration] Update case for auto-converge migration 

### ISSUE THREAD

**Issue by dzhengfy** [autotest/tp-libvirt#1679]
Internal requirements for below migrations.
- with --auto-converge
- with --auto-converge --auto-converge-initial  --auto-converge-increment 

https://github.com/autotest/tp-libvirt/pull/964 implement one of above, we need continue improvement.

**Comment by balamuruhans** [comment]
@dzhengfy This looks to be a good improvement for migration scenario.

**Comment by dzhengfy** [comment]
This is implemented in https://github.com/autotest/tp-libvirt/pull/2162.
