### ISSUE TITLE
Enable spell check in CI workflow

### ISSUE THREAD

**Issue by chunfuwen** [autotest/tp-libvirt#3722]
This practice is enabled in avocado-vt project, https://github.com/avocado-framework/avocado-vt/pull/3186.
It also help improve health of tp-libvirt project if we adopt it in tp-libvirt as well:
      - name: Run spellchecker
        run: pylint --errors-only --disable=all --enable=spelling --spelling-dict=en_US --spelling-private-dict-file=spell.ignore *

**Comment by chunfuwen** [comment]
```
[root@hp-dl360g9-16 tp-libvirt]# git push origin add_spell_check_in_ci --force
Username for 'https://github.com': chunfuwen
Password for 'https://chunfuwen@github.com': 
Enumerating objects: 10, done.
Counting objects: 100% (10/10), done.
Delta compression using up to 12 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (6/6), 8.20 KiB | 2.73 MiB/s, done.
Total 6 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/chunfuwen/tp-libvirt.git
 ! [remote rejected]   add_spell_check_in_ci -> add_spell_check_in_ci (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/ci.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/chunfuwen/tp-libvirt.git'

```

@ana 
I attempt to push one change to .github/workflows/ci.yml, and it warn me that I am  refused to allow a Personal Access Token to create or update workflow `.github/workflows/ci.yml` , do you know the reason?

**Comment by chunfuwen** [comment]
@kylazhang 
@dzhengfy 

Loop you them if you are interested

**Comment by ana** [comment]
@chunfuwen You need to give permissions to your Personal Access Token, look at this https://stackoverflow.com/questions/68811838/refusing-to-allow-a-personal-access-token-to-create-or-update-workflow

**Comment by chunfuwen** [comment]
@ana 
thanks you for your help, now it is working
