### ISSUE TITLE
'graphic_act' is not defined

### ISSUE THREAD

**Issue by svirt** [autotest/tp-libvirt#703]
Hello,

seems by accident the line *graphic_act = vmxml_act.devices.by_device_tag('graphics')[0]* was removed from virsh_domdisplay.py with the commit a1b76af30df3d562e2893f2f609129550f52178b , thus being a reason of the failure **NameError: global name 'graphic_act' is not defined**  in .. src/virsh_cmd/domain/virsh_domdisplay.py , line 140

I am not sure what was exactly supposed to be fixed  so I'd rather file an issue.

Thanks

**Comment by Hao-Liu** [comment]
@rbian, It seems your last commit to this test caused this failure. Please help fix this. Thanks.

**Comment by rbian** [comment]
Fixed in https://github.com/autotest/tp-libvirt/pull/705

**Comment by svirt** [comment]
Thanks. Works fine
