### ISSUE TITLE
snapshot_edit test failures

### ISSUE THREAD

**Issue by svirt** [autotest/tp-libvirt#707]
Hello,

maybe the problem is only  at my side (but actually it was working before the xml comparison changes) and I don't fully get the logic of the last changes in xml comparison code applied in the commit a1b76af30df3d562e2893f2f609129550f52178b  , but currently some of the snapshot_edit subtests fail with the error **TestFail: Failed xml before/after comparison** . In the past they were working fine.

Currently I have failures in
snapshot_edit.positive_tests.edit_option_clone.edit_option_current.*
snapshot_edit.positive_tests.edit_option_clone.edit_option_current.disk_snapshot.with_desc.*
snapshot_edit.positive_tests.edit_option_clone.edit_option_current.mem_snapshot.*
snapshot_edit.positive_tests.edit_option_clone.edit_option_snapname.internal_snapshot.*
....
....
and etc. in some other  subtests.

Could you please review it or advise me with it ? (maybe there is something related to the changes which I don't do correctly ). I am running those tests in Avocado.

Thanks

**Comment by will-Do** [comment]
@rbian 
Please help to check this issue, thx

**Comment by rbian** [comment]
@svirt , hope https://github.com/autotest/tp-libvirt/pull/708 can fix your problems.

**Comment by svirt** [comment]
@rbian 
Hi, thanks, I will test it and will let you know

**Comment by svirt** [comment]
@rbian 
Checked. All the tests passed. I guess it can be merged. Thanks

**Comment by will-Do** [comment]
@svirt Thanks for your feedback, and if you encounter any tp-libvirt bugs in the future, just raise them, and we would like to help fix them.
I'm going to close this issue per the last comment.

**Comment by svirt** [comment]
@will-Do 
Thank you for your support
